"""
Streamlit dashboard for the Trade Confirmation & Affirmation Copilot.

Run with:  streamlit run src/dashboard.py

Shows the full trade queue (affirmed + breaks), lets you drill into any
broken trade to see the detected field-level discrepancies, the agent's
break classification + severity rationale, and the drafted resolution
message ready for an analyst to review and send.
"""

import json
import os
import streamlit as st

st.set_page_config(page_title="Trade Confirmation & Affirmation Copilot", layout="wide")

REPORT_PATH = os.path.join(os.path.dirname(__file__), "..", "output", "exception_report.json")


@st.cache_data
def load_report():
    with open(REPORT_PATH) as f:
        return json.load(f)


def severity_badge(severity):
    colors = {"HIGH": "🔴", "MEDIUM": "🟠", "LOW": "🟢"}
    return f"{colors.get(severity, '⚪')} {severity}"


def main():
    st.title("Trade Confirmation & Affirmation Copilot")
    st.caption(
        "Agentic reasoning over trade confirmation breaks — matching, classification, "
        "and drafted resolution, end to end."
    )

    records = load_report()
    affirmed = [r for r in records if r["status"] == "AFFIRMED"]
    broken = [r for r in records if r["status"] == "BREAK"]

    col1, col2, col3 = st.columns(3)
    col1.metric("Total trades", len(records))
    col2.metric("Affirmed clean", len(affirmed))
    col3.metric("Breaks detected", len(broken))

    st.divider()

    tab_queue, tab_affirmed = st.tabs(["🚨 Exception Queue", "✅ Affirmed Trades"])

    with tab_queue:
        if not broken:
            st.success("No breaks detected — all trades affirmed clean.")
        for r in broken:
            severity = r.get("severity", "MEDIUM")
            with st.expander(
                f"{severity_badge(severity)}  {r['trade_id']}  —  {r['counterparty']}  "
                f"({r.get('break_category', 'unclassified')})"
            ):
                left, right = st.columns([1, 1])

                with left:
                    st.subheader("Detected discrepancy")
                    st.write(f"**Instrument:** {r['instrument_name']} ({r['isin']})")
                    for b in r["breaks"]:
                        st.write(
                            f"- **{b['field']}** — internal: `{b['internal_value']}` "
                            f"vs. external: `{b['external_value']}`"
                        )
                    st.write(f"**Classification:** {r.get('break_category', 'n/a')}")
                    st.write(f"**Severity:** {severity_badge(severity)}")
                    st.write(f"**Rationale:** {r.get('severity_rationale', 'n/a')}")
                    if r.get("mock"):
                        st.caption("⚠️ Generated by rule-based mock classifier (no live API key configured)")

                with right:
                    st.subheader("Drafted resolution message")
                    st.text_area(
                        "Ready to review and send:",
                        value=r.get("drafted_message", ""),
                        height=220,
                        key=f"msg_{r['trade_id']}",
                    )

    with tab_affirmed:
        st.write(f"{len(affirmed)} trades matched cleanly within tolerance.")
        header_cols = st.columns([2, 3, 3, 2])
        header_cols[0].markdown("**Trade ID**")
        header_cols[1].markdown("**Counterparty**")
        header_cols[2].markdown("**Instrument**")
        header_cols[3].markdown("**ISIN**")
        st.divider()
        for r in affirmed:
            cols = st.columns([2, 3, 3, 2])
            cols[0].write(r["trade_id"])
            cols[1].write(r["counterparty"])
            cols[2].write(r["instrument_name"])
            cols[3].write(r["isin"])


if __name__ == "__main__":
    main()
